Update terraform-pull-request.yml

diff --git a/.github/workflows/terraform-pull-request.yml b/.github/workflows/terraform-pull-request.yml
--- a/.github/workflows/terraform-pull-request.yml
+++ b/.github/workflows/terraform-pull-request.yml
@@ -13,7 +13,7 @@ on:
     #     type: boolean
 env:
   ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
-  ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
+  ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID_DEV }}"
   ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
   
 
@@ -21,6 +21,9 @@ jobs:
   terraform-pull-request:
     name: 'Terraform Pull Request'
     runs-on: ubuntu-latest
+    env:
+      #this is needed since we are running terraform with read-only permissions
+      ARM_SKIP_PROVIDER_REGISTRATION: true
 #    defaults:
 #      run:
 #        working-directory: ${{ env.tf_actions_working_dir }}
@@ -29,79 +32,104 @@ jobs:
     steps:
     - uses: actions/checkout@v3
     - uses: hashicorp/setup-terraform@v2
+      with:
+        terraform_wrapper: false
 
     # - name: Terraform fmt
     #   id: fmt
     #   run: terraform fmt -check
     #   continue-on-error: true
+    - name: Preparing Variables
+      id: prepvars
+      run: |
+        # Parse Azure secret into Terraform variables
+        echo "BRANCH_NAME=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_ENV
+      shell: bash
 
     - name: Terraform Init
       id: init
-      run: terraform init
-
+      #run: terraform init
+      # terraform init -backend-config=storage_account_name=tfstatefile01 -backend-config=container_name=tfstate -backend-config=key=dev-network.terraform.tstate -backend-config=resource_group_name=DefaultResourceGroup-EUS -backend-config=subscription_id=2a04288a-8136-4880-b526-c6070e59f004 -backend-config=tenant_id=37d20c78-05e3-416d-83ab-cdbc21fed22a -backend-config=client_id=*** -backend-config=client_secret=***
+      run: |
+        echo $BRANCH_NAME
     # - name: Terraform Validate
     #   id: validate
     #   run: terraform validate -no-color
 
+    #- name: Terraform Plan
+    #  id: plan
+    #  run: terraform plan -no-color
+    #  continue-on-error: true
+    
     - name: Terraform Plan
-      id: plan
-      run: terraform plan -no-color
-      continue-on-error: true
+      id: tf-plan
+      run: |
+        export exitcode=0
+     #   terraform plan -detailed-exitcode -no-color -out tfplan || export exitcode=$?
 
-    - uses: actions/github-script@v6
-      if: github.event_name == 'pull_request'
-      env:
-        PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
-      with:
-        github-token: ${{ secrets.GITHUB_TOKEN }}
-        script: |
-          // 1. Retrieve existing bot comments for the PR
-          const { data: comments } = await github.rest.issues.listComments({
-            owner: context.repo.owner,
-            repo: context.repo.repo,
-            issue_number: context.issue.number,
-          })
-          const botComment = comments.find(comment => {
-            return comment.user.type === 'Bot' && comment.body.includes('Terraform Format and Style')
-          })
+      #  echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
+        
+      #  if [ $exitcode -eq 1 ]; then
+      #    echo Terraform Plan Failed!
+      #    exit 1
+      #  else 
+      #    exit 0
+      #  fi
 
-          // 2. Prepare format of the comment
-          const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
-          #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
-          #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
-          <details><summary>Validation Output</summary>
-
-          \`\`\`\n
-          ${{ steps.validate.outputs.stdout }}
-          \`\`\`
-
-          </details>
-
-          #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
-
-          <details><summary>Show Plan</summary>
-
-          \`\`\`\n
-          ${process.env.PLAN}
-          \`\`\`
-
-          </details>
-
-          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;
-
-          // 3. If we have a comment, update it, otherwise create a new one
-          if (botComment) {
-            github.rest.issues.updateComment({
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              comment_id: botComment.id,
-              body: output
-            })
-          } else {
-            github.rest.issues.createComment({
-              issue_number: context.issue.number,
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              body: output
-            })
-          }
+    #- uses: actions/github-script@v6
+    #  if: github.event_name == 'pull_request'
+    #  env:
+    #    PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
+    #  with:
+    #    github-token: ${{ secrets.GITHUB_TOKEN }}
+    #    script: |
+    #      // 1. Retrieve existing bot comments for the PR
+    #      const { data: comments } = await github.rest.issues.listComments({
+    #        owner: context.repo.owner,
+    #        repo: context.repo.repo,
+    #        issue_number: context.issue.number,
+    #      })
+    #      const botComment = comments.find(comment => {
+    #        return comment.user.type === 'Bot' && comment.body.includes('Terraform Format and Style')
+    #      })
+    #
+    #      // 2. Prepare format of the comment
+    #      const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
+    #      #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
+    #      #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
+    #      <details><summary>Validation Output</summary>
+    #
+    #      \`\`\`\n
+    #      ${{ steps.validate.outputs.stdout }}
+    #      \`\`\`
+    #
+    #      </details>
+    #
+    #      #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
+    #
+    #      <details><summary>Show Plan</summary>
+    #
+    #      \`\`\`\n
+    #      ${process.env.PLAN}
+    #      \`\`\`
+    #
+    #      </details>
+    #
+    #      *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;
+    #
+    #      // 3. If we have a comment, update it, otherwise create a new one
+    #      if (botComment) {
+    #        github.rest.issues.updateComment({
+    #          owner: context.repo.owner,
+    #          repo: context.repo.repo,
+    #          comment_id: botComment.id,
+    #          body: output
+    #        })
+    #      } else {
+    #        github.rest.issues.createComment({
+    #          issue_number: context.issue.number,
+    #          owner: context.repo.owner,
+    #          repo: context.repo.repo,
+    #          body: output
+    #        })
+    #      }
