pr comment

diff --git a/.github/workflows/terraform-pull-request.yml b/.github/workflows/terraform-pull-request.yml
--- a/.github/workflows/terraform-pull-request.yml
+++ b/.github/workflows/terraform-pull-request.yml
@@ -84,17 +84,19 @@ jobs:
     #   run: terraform validate -no-color
 
     - name: Terraform Plan
-      id: plan
+      id: tf-plan
+      continue-on-error: true
       run: |
-        export exitcode=0
+        #export exitcode=0
         mkdir -p terraform-plan/${{ env.GITHUB_REPO }}
-        terraform plan -detailed-exitcode -out terraform-plan/${{ env.GITHUB_REPO }}/${{ env.GITHUB_REPO }}-${{ env.BRANCH_NAME }}.tfplan || export exitcode=$?
-        if [ $exitcode -eq 1 ]; then
-          echo Terraform Plan Failed!
-          exit 1
-        else
-          exit 0
-        fi
+        terraform plan -detailed-exitcode -out terraform-plan/${{ env.GITHUB_REPO }}/${{ env.GITHUB_REPO }}-${{ env.BRANCH_NAME }}.tfplan 
+        #|| export exitcode=$?
+        #if [ $exitcode -eq 1 ]; then
+        #  echo Terraform Plan Failed!
+        #  exit 1
+        #else
+        #  exit 0
+        #fi
     - uses: actions/upload-artifact@master
       with:
         name: ${{ env.GITHUB_REPO }}-${{ env.BRANCH_NAME }}.tfplan
@@ -118,7 +120,8 @@ jobs:
           })
     
           // 2. Prepare format of the comment
-          const output = `#### Terraform Plan 🖌 🤖 📖  \`${{ steps.tf-plan.outcome }}\`
+          const output = `#### Terraform Initialization ⚙️\`${{ steps.tf-init.outcome }}\`
+          `#### Terraform Plan 🖌 🤖 📖  \`${{ steps.tf-plan.outcome }}\`
     
           <details><summary>Show Plan</summary>
     
